services:
  crypto-track-price-bot:
    image: ${DOCKER_IMAGE}
    container_name: crypto-track-price-bot-${DEPLOY_ENV}
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ${VPS_WORKDIR}/${VPS_APP_FOLDER}/db:/app/prisma/db
    restart: unless-stopped
